# Generated by Django 5.0.3 on 2024-11-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_count_delete_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='countname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='count',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
