# Generated by Django 5.0.3 on 2024-11-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_count_countname_count_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='countname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='count',
            name='number',
            field=models.IntegerField(),
        ),
    ]
