# Generated by Django 5.0.3 on 2024-11-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_count_countname_alter_count_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
